### ISSUE TITLE
Run into this issue when running your scripts. I've tried excluding home as a target for the attacks and distribution with no luck. These issues pop up on loop and force me to kill all scripts.

### ISSUE THREAD

**Issue by pacmanninja998** [TheDroidYourLookingFor/BitBurner-Scripts#1]
Below are the Error codes given, any info is much appreciated.

RUNTIME ERROR
/TheDroid/weaken.js@home
Args: [""]

Assignment to constant variable.
stack:
TypeError: Assignment to constant variable.
at Module.main (/TheDroid/weaken.js:20:14)
at executeJSScript (file:///G:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:1:492770)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
RUNTIME ERROR
/TheDroid/hack.js@home
Args: [""]

Assignment to constant variable.
stack:
TypeError: Assignment to constant variable.
at Module.main (/TheDroid/hack.js:20:14)
at executeJSScript (file:///G:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:1:492770)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
RUNTIME ERROR
/TheDroid/grow.js@home
Args: [""]

Assignment to constant variable.
stack:
TypeError: Assignment to constant variable.
at Module.main (/TheDroid/grow.js:20:14)
at executeJSScript (file:///G:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:1:492770)

**Comment by TheDroidYourLookingFor** [comment]
Looks like you started grow/hack/weaken.ks without an argument. If you launch them from Manager-Deployment.js then it will read best_Target.txt which is generated from run nmap.js -> run Find.js

**Comment by TheDroidYourLookingFor** [comment]
Should be resolved in the latest push
