### ISSUE TITLE
Source-File-4

### ISSUE THREAD

**Issue by marcelolhe** [TheDroidYourLookingFor/BitBurner-Scripts#4]
For a begginer player like me, the script doesn't work, because i haven't any source files yet. I have the TOR server purchased manually, but the script didn't reconise that i have it. 

suggestion: put a verification if the player have the source file. if not, verify if the player have the TOR server already. If not, inform that the player neet it to continue.

**Comment by TheDroidYourLookingFor** [comment]
Its been moved into its own manager now for this reason
